sudo: required
services: 
    - docker

before_install:
    - docker build -t 271097/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run  -e CI=true 271097/react-test npm run test

after_success:
    - docker build -t 271097/multi-client ./client
    - docker build -t 271097/multi-nginx ./nginx
    - docker build -t 271097/multi-server ./server
    - docker build -t 271097/multi-worker ./worker
    #LOGIN TO DOCKER
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #PUSH THE IMAGES TO DOCKER HUB
    - docker push 271097/multi-client 
    - docker push 271097/multi-nginx 
    - docker push 271097/multi-server 
    - docker push 271097/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-573607591379
    bucket_path: docker-multi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY